spring.application.name=navalstrikeAPI

#Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true

#JPA
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-hours=2

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# OpenTelemetry Tracing -> Jaeger
management.opentelemetry.tracing.export.otlp.endpoint=http://jaeger:4318/v1/traces
management.tracing.sampling.probability=1.0


# Hibernate metrics
spring.jpa.properties.hibernate.generate_statistics=true

# Habilitar histogramas para percentis (P95, P99)
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Habilitar metricas do HikariCP
spring.datasource.hikari.register-mbeans=true