spring.application.name=navalstrikeAPI

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/navalstrike
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=SUA_CHAVE_SECRETA_AQUI
jwt.expiration-hours=2
